### ISSUE TITLE
change tire pressure on crawlers

### ISSUE THREAD

**Issue by deutzfahraustria** [RealismusModding/FS17_RM_soilCompaction#10]
Hello,
at the moment you can change the tire pressure on tractors with crawlers like the Challenger MT800E
it uses tireType="crawler" in the wheels entries, and this could be checked and disabled if true.

**Comment by deutzfahraustria** [comment]
Also, it uses the "fake wheels" to calculate the compaction. So it shows heavy compaction without anything attached.
Area which touches the ground probably could be calculated with the width of the wheels and scrollLength*0.5 from the crawler

**Comment by stijnwop** [comment]
Mm, actually we do check on crawlers. Will have a look at it.

Thanks for your report.

**Comment by reallogger** [comment]
The issues should be fixed now. Thanks for testing.

**Comment by reallogger** [comment]
Need to add a check if someone includes incab pressure control on a crawler mod

**Comment by deutzfahraustria** [comment]
works perfect now, thanks for the fix!
