### ISSUE TITLE
Virtual vs. Physical wheels

### ISSUE THREAD

**Issue by KITT3000** [RealismusModding/FS17_RM_soilCompaction#12]
The change in air pressure only affects wheel models visible in the game. After lowering the pressure, the wheels break away from the axle, instead of lowering the entire vehicle.

PS. Is currently changing pressure only works on vehicles or in machines/trailers also should (information about soil compaction appears, but pressure can not be changed).

**Comment by reallogger** [comment]
Yes, that the axle does not follow the wheel is a known issue (#3). 

Currently changing pressure is only possible on Motorized, but we are looking into expanding it.
