### ISSUE TITLE
Callstack Crawlers

### ISSUE THREAD

**Issue by CityFarmerDE** [RealismusModding/FS17_RM_soilCompaction#14]
Hi,

Case Magnum CVX (Crawler Version), NH 1090 Harvester and Case Quadtrac cause a Lua Callstack. Challenger MT is working. The Callstack occurs if you enter the vehicle range, that starts to show  the compaction in the F1 Menue.
 I guess it happens only to vehicles with more than 2 Crawlers.

.../FS17_RM_soilCompaction/src/scSoilCompaction.lua:72: attempt to index field 'baseNode' (a number value)
Error: Running LUA method 'update'.

**Comment by reallogger** [comment]
Works now
