### ISSUE TITLE
Dual/Tripple wheels are not taken into account.

### ISSUE THREAD

**Issue by mrbear** [RealismusModding/FS17_RM_soilCompaction#21]
It seams that adding wheels does not have any or effekt or adds to ground compaction.

MT900E with single wheels causes low compaction.
MT900E with tripple wheels causes medium compaction.

900 Vario with single wheels causes low compaction.
900 Vario with single wheels causes medium compaction.

Narrow wheels seams to work

700 Vario with narrow wheels creates medium compaction
700 Vario with wide wheels creates low compaction

The problem might be that we don't take the width of wheel.additionalWheels into account.

**Comment by reallogger** [comment]
The width is now taken into account with twin and triple wheels. But I still get low compaction with MT900E with single wheels and medium compaction when using triple wheels. Will look further into it.

**Comment by mrbear** [comment]
Should you not add the width of the additional wheels to width around line 90?

This is what I did when I was working on it:

    if wheel.additionalWheels ~= nil then
        for _,additionalWheel in pairs(wheel.additionalWheels) do
            width=width + additionalWheel.width
        end
    end

**Comment by reallogger** [comment]
yeah forgot that one. Should be working now.
