### ISSUE TITLE
Cant join on Dedi Server

### ISSUE THREAD

**Issue by derelky** [RealismusModding/FS17_RM_soilCompaction#26]
Hello,

when the Mod is active it freeze at sync.
On the Server we get this error

...mods/FS17_RM_soilCompaction/src/vehicles/scTirePressure.lua:101: attempt to call global 'streamWriteInt' (a nil value)

we tested it with standard Map and only this mod.

**Comment by stijnwop** [comment]
Hey, yes this is known because it's not even close to be MP ready.

We are working on that, but for now the mod just works in SP.
