### ISSUE TITLE
just a question regarding the scCultivation

### ISSUE THREAD

**Issue by mrPassion78** [RealismusModding/FS17_RM_soilCompaction#33]
Hi there, i want to go and add the scCultivation tag into all my MR-conversions, that work with the soil, but i just wanted to ask where to put it..
Can it put in the xml like a solo line, or does it need anything else?

when i copied the lines needed a few days ago from this site it say`d this: 
<scCultivation>deep</scCultivation>
    <scCultivation>subsoiler</scCultivation>	
    <scCultivation deep="true" />
    <scCultivation subsoiler="true" />

now only the last 2 lines exist.

i already added the line for tire pressure in conversions and that works like a charm.. i really like this guys, so thnx a lot for adding this to Farmsim.

greetings Passion78

edit:
i have the Karcher mod installed that is( i believe) form you guys, and on buying the mod, the soilCompaction gives an error:
C:/Users/passion/Documents/My Games/FarmingSimulator2017/mods/FS17_Kaercher_Mobile_HPW/kaercher_washTrailer.i3d (197.10) ms
Error: Running LUA method 'update'.
C:/Users/passion/Documents/My Games/FarmingSimulator2017/mods/ZZZZZZ_RM_soilCompaction/src/vehicles/scSoilCompaction.lua:325: attempt to call method 'isPlayerInRange' (a boolean value)

i hope you know what that might mean.. 
greetings

**Comment by stijnwop** [comment]
What exactly did you add to your cultivator xmls?

You know that it's not necessarily needed to add those lines to you xml? The logic is added as soon the vehicle has the vanilla Cultivator spec. If you want to force subsoilers or deep cultivators you could add the xml entries.

The entries can be found in the readme:
https://github.com/RealismusModding/FS17_RM_soilCompaction#decompacting-the-soil

About the error.. it seems like your mod overwrites the isPlayerInRange method that we use to a boolean. Looks like a mod conflict with the Kaercher.

We could prefix our method.. will think about it. 😄

**Comment by mrPassion78** [comment]
thanx for the comment..
I realy like the whole soilcompaction, adds even more to realism..

And sins i did not quite understand when to put the lines in the xml, i understand now that it is only needed for the ploughs and deep subsoilers ( like the lemken dolomit)[https://www.farming-simulator.com/mod.php?lang=en&country=nl&mod_id=63185&title=fs2017](url)
that would then require the attribute:  <scCultivation deep="true" />
<scCultivation subsoiler="true" />

please correct if i`m wrong.

thnx for all the amazing work.

**Comment by stijnwop** [comment]
If it's mod yes. You will have to add the xml entry.
