### ISSUE TITLE
couple of questions..

### ISSUE THREAD

**Issue by doc3d** [RealismusModding/FS17_RM_soilCompaction#34]
Im finding this very interesting, just wondering about a couple things, if I may..

What is the effect on grassfields? I mean, does compaction decrease over time, or would you have to plow your grassfield when it gets compacted, like the regurlar fields? Since the default plowing is not needed, I was wondering how that works with the SC mod. 

Does the compaction affect anything like growth or yield, or is it purely cosmetic at this point?

When you sow a freshly plowed field, the sower seems to make the whole field lightly compacted again, so you basically always have a compacted field, is this correct?

Thanks for once again upping the realism, its greatly appreciated.

**Comment by joskuijpers** [comment]
SC mod affects the plow layer which already affects yield. More compaction = less yield.

The other two I myself don't know the answer too. For the tractors with sowing: use deflated tires or wider tires. Or use small tired and forego any yield from those small lanes.

**Comment by doc3d** [comment]
Thank you, jos
Ok, if the yield is affected, there should probably be some way to remove compaction in grass-fields, I would think. Having to plow the grass several times per season seems a bit strange. 

With arable fields, If just the tires would compact the ground I could understand it, but the sower compacts as well across the whole width, so when seeding, after you are done, the whole field is pink. The only way to remove this light compaction would be to cultivate or plow, which would then make you have to seed again, and that’s full circle. This is the part I don’t understand, basically it’s impossible to have anything less than light compaction across the whole field, then...? 
And since most of the tractors and implements I use have low compaction, I can drive back and forth all day long without it getting any worse since the field already has light compaction from the sower. 
I might have done something wrong when installing, but it seems to work -it’s just not working as I would expect it to

**Comment by reallogger** [comment]
It is possible to plant fields without giving any compaction. It all depends on what equipment you use. We are considering a couple of options for grass fields.
