### ISSUE TITLE
not a issue, just a question / idea

### ISSUE THREAD

**Issue by SbSh-DNA-ModDing** [RealismusModding/FS17_RM_soilCompaction#36]
Is it possible to make a xml entry like `<scInCabTirePressureControl>true</scInCabTirePressureControl>`,
that adjust the compaction level, what the vehicle has. All heavy machines has light compaction, thats not really real^^

An Entry what could looks like `<SetCompactionLevel SCL="none|light|medium|heavy" />`
Or Set in the buy options to change by tiresetups
Just an idea... 
best regards

**Comment by reallogger** [comment]
There is an underlying physical model (based on scientific papers on the subject) that determines ground pressure and the pressure propagation into the soil to calculate the soil compaction. The compaction level a vehicle gives depends on, not only its mass, but also the ground wetness. So when the ground is completely dry, most tractors give no or light compaction. Some of the heaviest ones might give medium. But the real difference can be noticed when the ground is wet. Then the smallest tractors will still give no or light compaction, but the larger tractors will give medium or heavy compaction.

 Also the compaction a tractor gives will depend on what implements it carries. Mount a large front weight and a plough on the back and you'll see the induced compaction level increasing.

Thanks for the suggestion, but we won't implement such a deterministic solution :)

**Comment by SbSh-DNA-ModDing** [comment]
okay nice answer, like this it's understandable for everyone, thank you.
