### ISSUE TITLE
tractors do not get over 30km/h with 1.30 bar

### ISSUE THREAD

**Issue by cabmac** [RealismusModding/FS17_RM_soilCompaction#38]
Hi...curiuos thing, taking pressure off any tractors wheels (original AND mods), they don`t get over, lets say 30km/h....30km/h when i take pressure to 1.30 for example. If i take pressure off to 1.40 then i have 42 km/h....and so on.....i play with gearbox but i don`t think that that has anything to do with that...?

**Comment by reallogger** [comment]
Try latest commit. Should be back to normal now ;)
