### ISSUE TITLE
Air compressor generates errors

### ISSUE THREAD

**Issue by KITT3000** [RealismusModding/FS17_RM_soilCompaction#5]
I bought an air compressor, put it on the ground, went over and turned it on and the HUDs started to flash, the entries in the help window multiplied, and there were such errors in the LOG.
LOG: https://gist.github.com/KITT3000/204d6458abd778007a5be40024f5ce89

**Comment by reallogger** [comment]
There was also another error in the log, which now is fixed. Please try latest version.

If that does not help, please check that you have ACTIVATE_HANDTOOL and ACTIVATE_HANDTOOL2 in the inputBinding.xml

**Comment by KITT3000** [comment]
I have checked and in `inputBinding.xml` I do not have such a button as **ACTIVATE_HANDTOOL2**, and I do not have it in `.../Farming Simulator 17/profileTemplate/inputBindingDefault.xml`. So you probably only have this button from some other mod.

**edit**
After adding to modDesc 
`<input name="ACTIVATE_HANDTOOL2" category="ONFOOT" key1="KEY_z" key2="" device="1" button="" mouse="MOUSE_BUTTON_RIGHT" visible="true"/>`
there are no errors and everything works.

**Comment by reallogger** [comment]
Thanks. Included this now in 17d1a71.
