### ISSUE TITLE
Harvesting Callstack

### ISSUE THREAD

**Issue by CityFarmerDE** [RealismusModding/FS17_RM_soilCompaction#9]
If I try to harvest crops, it gets a callstack and every soil compaction at the map will be removed.

.../FS17_RM_soilCompaction/src/scCompactionManager.lua:97: attempt to call local 'superFunc' (a number value)
Error: Running LUA method 'update'.

Vanilla Game, new Savegame, Case Cutter

**Comment by reallogger** [comment]
Working now. Thanks for reporting.
